### ISSUE TITLE
Weird page layout

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/budget-portal#78]
The layout on this page looks broken
<img width="1080" alt="screen shot 2018-08-24 at 10 58 34" src="https://user-images.githubusercontent.com/420786/44575717-ee4bb880-a78c-11e8-9c47-f2546c63ad0a.png">

**Comment by jbothma** [comment]
Do you mean the big gap?

It should be like this, but they couldn't provide the mandate data and it was too laborious for us to do it again

![vulemamali-mpumalanga-education-2017-18](https://user-images.githubusercontent.com/235801/44575901-8053c100-a78d-11e8-868e-39952a2321ce.png)
